import "./globals.css";
import { Nunito, Open_Sans } from 'next/font/google'

const nunito = Nunito({
    subsets: ['latin'],
    display: "swap",
    variable: '--font-nunito',
})

const sans = Open_Sans({
  subsets: ['latin'],
  display: "swap",
  variable: '--font-sans',
})

export const metadata = {
  title: "Project X",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/favicons/favicon-light.ico',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/favicons/favicon-dark.ico',
        media: '(prefers-color-scheme: dark)',
      },
    ],
  },
}

const RootLayout = ({ children }) => {
  return (
    <html lang="pl" className={`${nunito.variable} ${sans.variable}`}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout